// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Platform  Firebase App Id
// web       1:590006646893:web:aaec34fc041b814c8ea764
// android   1:590006646893:android:f9c186424488e6398ea764
// ios       1:590006646893:ios:ef424ac54a1dd76d8ea764
// macos     1:590006646893:ios:ef424ac54a1dd76d8ea764
// windows   1:590006646893:web:eff038afd19e2bad8ea764


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwLDkASMcIWdkRN2Mx9B23QPtsM4VNy0o',
    appId: '1:590006646893:web:aaec34fc041b814c8ea764',
    messagingSenderId: '590006646893',
    projectId: 'meds-53264',
    authDomain: 'meds-53264.firebaseapp.com',
    storageBucket: 'meds-53264.firebasestorage.app',
    measurementId: 'G-CMRRKQX9FH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd9K8qNnBnhHnDdYcFtyu6GKaNcct9Egc',
    appId: '1:590006646893:android:f9c186424488e6398ea764',
    messagingSenderId: '590006646893',
    projectId: 'meds-53264',
    storageBucket: 'meds-53264.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDqcvTyULCxDCZw1AeR-a7mRPeXPiHYU8',
    appId: '1:590006646893:ios:ef424ac54a1dd76d8ea764',
    messagingSenderId: '590006646893',
    projectId: 'meds-53264',
    storageBucket: 'meds-53264.firebasestorage.app',
    iosBundleId: 'com.example.meds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDqcvTyULCxDCZw1AeR-a7mRPeXPiHYU8',
    appId: '1:590006646893:ios:ef424ac54a1dd76d8ea764',
    messagingSenderId: '590006646893',
    projectId: 'meds-53264',
    storageBucket: 'meds-53264.firebasestorage.app',
    iosBundleId: 'com.example.meds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwLDkASMcIWdkRN2Mx9B23QPtsM4VNy0o',
    appId: '1:590006646893:web:eff038afd19e2bad8ea764',
    messagingSenderId: '590006646893',
    projectId: 'meds-53264',
    authDomain: 'meds-53264.firebaseapp.com',
    storageBucket: 'meds-53264.firebasestorage.app',
    measurementId: 'G-NYCXFM1BG1',
  );

}